// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/network_access_provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkAccessProvider_Connect_FullMethodName    = "/silo.plugin.v1.NetworkAccessProvider/Connect"
	NetworkAccessProvider_Disconnect_FullMethodName = "/silo.plugin.v1.NetworkAccessProvider/Disconnect"
	NetworkAccessProvider_GetStatus_FullMethodName  = "/silo.plugin.v1.NetworkAccessProvider/GetStatus"
)

// NetworkAccessProviderClient is the client API for NetworkAccessProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NetworkAccessProvider gives a Silo deployment an overlay-network identity
// (Tailscale, NetBird, ...). The plugin owns the overlay client and a reverse
// proxy in front of the host listeners it learns from RuntimeHost.GetHostInfo;
// the host owns supervision, per-instance state storage, status aggregation,
// and the admin API. Plugins declaring this capability are resident: the host
// starts them at boot, restarts them on crash, and stops them last.
type NetworkAccessProviderClient interface {
	// Connect brings the overlay identity up and starts proxying. It returns the
	// status reached so far; enrollment may continue in the background and be
	// reported through RuntimeHost.ReportNetworkAccessStatus.
	Connect(ctx context.Context, in *NetworkAccessConnectRequest, opts ...grpc.CallOption) (*NetworkAccessStatus, error)
	// Disconnect tears the overlay listener down and clears desired_connected.
	Disconnect(ctx context.Context, in *NetworkAccessDisconnectRequest, opts ...grpc.CallOption) (*NetworkAccessStatus, error)
	// GetStatus returns the current status without changing it.
	GetStatus(ctx context.Context, in *NetworkAccessGetStatusRequest, opts ...grpc.CallOption) (*NetworkAccessStatus, error)
}

type networkAccessProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkAccessProviderClient(cc grpc.ClientConnInterface) NetworkAccessProviderClient {
	return &networkAccessProviderClient{cc}
}

func (c *networkAccessProviderClient) Connect(ctx context.Context, in *NetworkAccessConnectRequest, opts ...grpc.CallOption) (*NetworkAccessStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkAccessStatus)
	err := c.cc.Invoke(ctx, NetworkAccessProvider_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAccessProviderClient) Disconnect(ctx context.Context, in *NetworkAccessDisconnectRequest, opts ...grpc.CallOption) (*NetworkAccessStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkAccessStatus)
	err := c.cc.Invoke(ctx, NetworkAccessProvider_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAccessProviderClient) GetStatus(ctx context.Context, in *NetworkAccessGetStatusRequest, opts ...grpc.CallOption) (*NetworkAccessStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkAccessStatus)
	err := c.cc.Invoke(ctx, NetworkAccessProvider_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkAccessProviderServer is the server API for NetworkAccessProvider service.
// All implementations should embed UnimplementedNetworkAccessProviderServer
// for forward compatibility.
//
// NetworkAccessProvider gives a Silo deployment an overlay-network identity
// (Tailscale, NetBird, ...). The plugin owns the overlay client and a reverse
// proxy in front of the host listeners it learns from RuntimeHost.GetHostInfo;
// the host owns supervision, per-instance state storage, status aggregation,
// and the admin API. Plugins declaring this capability are resident: the host
// starts them at boot, restarts them on crash, and stops them last.
type NetworkAccessProviderServer interface {
	// Connect brings the overlay identity up and starts proxying. It returns the
	// status reached so far; enrollment may continue in the background and be
	// reported through RuntimeHost.ReportNetworkAccessStatus.
	Connect(context.Context, *NetworkAccessConnectRequest) (*NetworkAccessStatus, error)
	// Disconnect tears the overlay listener down and clears desired_connected.
	Disconnect(context.Context, *NetworkAccessDisconnectRequest) (*NetworkAccessStatus, error)
	// GetStatus returns the current status without changing it.
	GetStatus(context.Context, *NetworkAccessGetStatusRequest) (*NetworkAccessStatus, error)
}

// UnimplementedNetworkAccessProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkAccessProviderServer struct{}

func (UnimplementedNetworkAccessProviderServer) Connect(context.Context, *NetworkAccessConnectRequest) (*NetworkAccessStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNetworkAccessProviderServer) Disconnect(context.Context, *NetworkAccessDisconnectRequest) (*NetworkAccessStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedNetworkAccessProviderServer) GetStatus(context.Context, *NetworkAccessGetStatusRequest) (*NetworkAccessStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNetworkAccessProviderServer) testEmbeddedByValue() {}

// UnsafeNetworkAccessProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkAccessProviderServer will
// result in compilation errors.
type UnsafeNetworkAccessProviderServer interface {
	mustEmbedUnimplementedNetworkAccessProviderServer()
}

func RegisterNetworkAccessProviderServer(s grpc.ServiceRegistrar, srv NetworkAccessProviderServer) {
	// If the following call panics, it indicates UnimplementedNetworkAccessProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkAccessProvider_ServiceDesc, srv)
}

func _NetworkAccessProvider_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkAccessConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAccessProviderServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAccessProvider_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAccessProviderServer).Connect(ctx, req.(*NetworkAccessConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAccessProvider_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkAccessDisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAccessProviderServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAccessProvider_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAccessProviderServer).Disconnect(ctx, req.(*NetworkAccessDisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAccessProvider_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkAccessGetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAccessProviderServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAccessProvider_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAccessProviderServer).GetStatus(ctx, req.(*NetworkAccessGetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkAccessProvider_ServiceDesc is the grpc.ServiceDesc for NetworkAccessProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkAccessProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.NetworkAccessProvider",
	HandlerType: (*NetworkAccessProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _NetworkAccessProvider_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _NetworkAccessProvider_Disconnect_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NetworkAccessProvider_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/network_access_provider.proto",
}
