// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/network_access_provider.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkAccessConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAccessConnectRequest) Reset() {
	*x = NetworkAccessConnectRequest{}
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccessConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccessConnectRequest) ProtoMessage() {}

func (x *NetworkAccessConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccessConnectRequest.ProtoReflect.Descriptor instead.
func (*NetworkAccessConnectRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP(), []int{0}
}

type NetworkAccessDisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAccessDisconnectRequest) Reset() {
	*x = NetworkAccessDisconnectRequest{}
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccessDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccessDisconnectRequest) ProtoMessage() {}

func (x *NetworkAccessDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccessDisconnectRequest.ProtoReflect.Descriptor instead.
func (*NetworkAccessDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP(), []int{1}
}

type NetworkAccessGetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAccessGetStatusRequest) Reset() {
	*x = NetworkAccessGetStatusRequest{}
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccessGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccessGetStatusRequest) ProtoMessage() {}

func (x *NetworkAccessGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccessGetStatusRequest.ProtoReflect.Descriptor instead.
func (*NetworkAccessGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP(), []int{2}
}

// NetworkAccessStatus is the provider's view of one plugin instance. Every
// host (API server, each proxy node) runs its own instance and reports its own
// status; the host aggregates them.
type NetworkAccessStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of: disconnected | awaiting_authorization | connecting | connected | error.
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Overlay DNS name, e.g. silo.tail1234.ts.net.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// scheme://host[:port] clients should use for the api listener.
	Origin string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	// Overlay IP addresses assigned to this instance.
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// One entry per exposed host listener (see RuntimeHost.GetHostInfo).
	Listeners []*NetworkAccessListener `protobuf:"bytes,5,rep,name=listeners,proto3" json:"listeners,omitempty"`
	// Interactive enrollment URL. Only set while state is awaiting_authorization.
	// Admin-only; the plugin must never log it.
	AuthUrl string `protobuf:"bytes,6,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	// Human-readable failure detail when state is error.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// Provider client version shown to admins, e.g. "tsnet 1.102.4".
	ProviderVersion string `protobuf:"bytes,8,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"`
	// Plugin-owned intent that survives restarts. The plugin persists it in
	// instance state and reconnects on start when true.
	DesiredConnected bool `protobuf:"varint,9,opt,name=desired_connected,json=desiredConnected,proto3" json:"desired_connected,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkAccessStatus) Reset() {
	*x = NetworkAccessStatus{}
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccessStatus) ProtoMessage() {}

func (x *NetworkAccessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccessStatus.ProtoReflect.Descriptor instead.
func (*NetworkAccessStatus) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkAccessStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NetworkAccessStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NetworkAccessStatus) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *NetworkAccessStatus) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NetworkAccessStatus) GetListeners() []*NetworkAccessListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *NetworkAccessStatus) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *NetworkAccessStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NetworkAccessStatus) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *NetworkAccessStatus) GetDesiredConnected() bool {
	if x != nil {
		return x.DesiredConnected
	}
	return false
}

// NetworkAccessListener maps one host listener onto its overlay origin.
type NetworkAccessListener struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listener name from RuntimeHost.GetHostInfo: api | jellyfin | abs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Overlay origin serving that listener, scheme://host[:port].
	Origin        string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAccessListener) Reset() {
	*x = NetworkAccessListener{}
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccessListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccessListener) ProtoMessage() {}

func (x *NetworkAccessListener) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccessListener.ProtoReflect.Descriptor instead.
func (*NetworkAccessListener) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkAccessListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkAccessListener) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// NetworkAccessProviderDescriptor is the typed manifest metadata for a
// network_access_provider.v1 capability. The host lists providers from it
// without launching the plugin.
type NetworkAccessProviderDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable provider slug, e.g. "tailscale", "netbird". Lowercase, path-safe.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Operator-facing name, e.g. "Tailscale".
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAccessProviderDescriptor) Reset() {
	*x = NetworkAccessProviderDescriptor{}
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAccessProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAccessProviderDescriptor) ProtoMessage() {}

func (x *NetworkAccessProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_network_access_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAccessProviderDescriptor.ProtoReflect.Descriptor instead.
func (*NetworkAccessProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkAccessProviderDescriptor) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *NetworkAccessProviderDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_silo_plugin_v1_network_access_provider_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_network_access_provider_proto_rawDesc = "" +
	"\n" +
	",silo/plugin/v1/network_access_provider.proto\x12\x0esilo.plugin.v1\"\x1d\n" +
	"\x1bNetworkAccessConnectRequest\" \n" +
	"\x1eNetworkAccessDisconnectRequest\"\x1f\n" +
	"\x1dNetworkAccessGetStatusRequest\"\xcb\x02\n" +
	"\x13NetworkAccessStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12C\n" +
	"\tlisteners\x18\x05 \x03(\v2%.silo.plugin.v1.NetworkAccessListenerR\tlisteners\x12\x19\n" +
	"\bauth_url\x18\x06 \x01(\tR\aauthUrl\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12)\n" +
	"\x10provider_version\x18\b \x01(\tR\x0fproviderVersion\x12+\n" +
	"\x11desired_connected\x18\t \x01(\bR\x10desiredConnected\"C\n" +
	"\x15NetworkAccessListener\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\"`\n" +
	"\x1fNetworkAccessProviderDescriptor\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName2\xb8\x02\n" +
	"\x15NetworkAccessProvider\x12[\n" +
	"\aConnect\x12+.silo.plugin.v1.NetworkAccessConnectRequest\x1a#.silo.plugin.v1.NetworkAccessStatus\x12a\n" +
	"\n" +
	"Disconnect\x12..silo.plugin.v1.NetworkAccessDisconnectRequest\x1a#.silo.plugin.v1.NetworkAccessStatus\x12_\n" +
	"\tGetStatus\x12-.silo.plugin.v1.NetworkAccessGetStatusRequest\x1a#.silo.plugin.v1.NetworkAccessStatusBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_network_access_provider_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_network_access_provider_proto_rawDescData []byte
)

func file_silo_plugin_v1_network_access_provider_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_network_access_provider_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_network_access_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_network_access_provider_proto_rawDesc), len(file_silo_plugin_v1_network_access_provider_proto_rawDesc)))
	})
	return file_silo_plugin_v1_network_access_provider_proto_rawDescData
}

var file_silo_plugin_v1_network_access_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_silo_plugin_v1_network_access_provider_proto_goTypes = []any{
	(*NetworkAccessConnectRequest)(nil),     // 0: silo.plugin.v1.NetworkAccessConnectRequest
	(*NetworkAccessDisconnectRequest)(nil),  // 1: silo.plugin.v1.NetworkAccessDisconnectRequest
	(*NetworkAccessGetStatusRequest)(nil),   // 2: silo.plugin.v1.NetworkAccessGetStatusRequest
	(*NetworkAccessStatus)(nil),             // 3: silo.plugin.v1.NetworkAccessStatus
	(*NetworkAccessListener)(nil),           // 4: silo.plugin.v1.NetworkAccessListener
	(*NetworkAccessProviderDescriptor)(nil), // 5: silo.plugin.v1.NetworkAccessProviderDescriptor
}
var file_silo_plugin_v1_network_access_provider_proto_depIdxs = []int32{
	4, // 0: silo.plugin.v1.NetworkAccessStatus.listeners:type_name -> silo.plugin.v1.NetworkAccessListener
	0, // 1: silo.plugin.v1.NetworkAccessProvider.Connect:input_type -> silo.plugin.v1.NetworkAccessConnectRequest
	1, // 2: silo.plugin.v1.NetworkAccessProvider.Disconnect:input_type -> silo.plugin.v1.NetworkAccessDisconnectRequest
	2, // 3: silo.plugin.v1.NetworkAccessProvider.GetStatus:input_type -> silo.plugin.v1.NetworkAccessGetStatusRequest
	3, // 4: silo.plugin.v1.NetworkAccessProvider.Connect:output_type -> silo.plugin.v1.NetworkAccessStatus
	3, // 5: silo.plugin.v1.NetworkAccessProvider.Disconnect:output_type -> silo.plugin.v1.NetworkAccessStatus
	3, // 6: silo.plugin.v1.NetworkAccessProvider.GetStatus:output_type -> silo.plugin.v1.NetworkAccessStatus
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_network_access_provider_proto_init() }
func file_silo_plugin_v1_network_access_provider_proto_init() {
	if File_silo_plugin_v1_network_access_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_network_access_provider_proto_rawDesc), len(file_silo_plugin_v1_network_access_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_network_access_provider_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_network_access_provider_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_network_access_provider_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_network_access_provider_proto = out.File
	file_silo_plugin_v1_network_access_provider_proto_goTypes = nil
	file_silo_plugin_v1_network_access_provider_proto_depIdxs = nil
}
